const languagePack = [
  [
    "ukr",
    {
      name: "UKR",
      background: "button-ukr",
      header: "Погода & карта",
      placeholder: "Введіть місто",
      btnShow: "Показати",
      btn5Days: "На 5 днів",
      btnCurrent: "Поточний",
      unchosenCity: "Місто не визначено",
      fetchLang: "ua",
      locationPlaceholder: "Розташування не задано",
      dateFormat: "ua-UA",
      wind: {
        ne: "ПН-СХ",
        e: "СХ",
        se: "ПД-СХ",
        s: "ПД",
        sw: "ПД-ЗХ",
        w: "ЗХ",
        nw: "ПН-ЗХ",
        n: "ПН",
      },
      date: "Дата",
      time: "Час",
      sunrise: "Схід сонця",
      sunset: "Захід сонця",
      press: "Тиск",
      windSpeed: "Вітер",
      mSec: "м/с",
      clouds: "Хмарність",
      fact: "Фактично",
      feels: "Відчувається",
      humidity: "Вологість",
      errorMsg: "Збережених міст не знайдено",
      dellBtn: "Видалити",
      chosen: "Обрані",
      addCoords: "Додати поточні координати",
      clearAll: "Очистити все",
      errorCountry: "Помилка! Не вдалось отримати дані країни",
      errorCity: "Помилка! Не вдалось отримати дані міста",
      errorMap: "Помилка! Не вдалось отримати дані з карти",
      infoHeader: 'Можливості додатку',
      infoLi1: 'Прапор країни - мова додатку',
      infoLi2: 'Обрані локації - можливість формувати перелік улюблених міст для швидкого доступу до погоди',
      infoLi3: 'Запит погоди відповідно до поточних координат',
      infoLi4: 'Запит погоди відповідно до введеної назви міста',
      infoLi5: 'На карті відображаються координати обраного міста. Також є можливість обирати нові координати за допомогою маркеру',
    },
  ],
  [
    "uk",
    {
      name: "ENG",
      background: "button-uk",
      header: "Weather & map",
      placeholder: "Enter the city",
      btnShow: "Show",
      btn5Days: "For 5 days",
      btnCurrent: "Current",
      unchosenCity: "The city is not chosen",
      fetchLang: "en",
      locationPlaceholder: "Location is not specified",
      dateFormat: "en-EN",
      wind: {
        ne: "NE",
        e: "E",
        se: "SE",
        s: "S",
        sw: "SW",
        w: "W",
        nw: "NW",
        n: "N",
      },
      date: "Date",
      time: "Time",
      sunrise: "Sunrise",
      sunset: "Sunset",
      press: "Pressure",
      windSpeed: "Wind",
      mSec: "m/s",
      clouds: "Clouds",
      fact: "Actually",
      feels: "Feels like",
      humidity: "Humidity",
      errorMsg: "No saved cities",
      dellBtn: "Delete",
      chosen: "Favourites",
      addCoords: "Add current coordinates",
      clearAll: "Clear all",
      errorCountry: "Error! Can't receive country data",
      errorCity: "Error! Can't receive city data",
      errorMap: "Error! Can't receive map data",
      infoHeader: 'App features',
      infoLi1: 'Country flag - app language',
      infoLi2: 'Favorite locations - posibility to form a list of favorite sities for fast access to weather forecast',
      infoLi3: 'Weather request according to current coordinates',
      infoLi4: 'Weather reques according to input city name',
      infoLi5: 'Current city coordinates are displayed on the map. Also it is possible to choose new coordinates using marker',
    },
  ],
];

export default languagePack;
